### PR TITLE
Fixing some issues I found running this for the first time

### PR DESCRIPTION
**Pull request by pbevan1**
Hi,

Thanks for the code & research! I attempted to follow the README to get this running, and found a couple of issues:

- fireworks-ai missing from the requirements.txt
- bash command in README seems out of sync with the codebase - some of the args weren't recognised, I attempted here to update the README wrt the code, maybe double check this is fine
- The organization seemed to be set to OWAIN_ORG in many places. I switched this to DEFAULT_ORG in line with the README secrets file instructions

Thanks,

Peter

### CODE REVIEW

**Comment by felixbinder** [comment]
Thanks Peter, we really appreciate your contribution! I've gone ahead and merged it—let us know how things go working with the codebase

**Comment by pbevan1** [comment]
Thanks Felix. I got it up and running fine after that!

My intention is to try some experiments to see if it's possible to get more robust/generalisable introspection. One idea was to try a curriculum learning type approach and order the finetuning data by increasing complexity of the response property. My budget is low so initially I've tried with 4o-mini (with gpt4o for cross prediction), and the initial experiments indicate that curriculum learning doesn't seem to help, but also just generally seeing weak evidence of introspection.

Perhaps the model is just not capable enough, similar to your findings on gpt-3.5.. Also now wondering if using gpt4o for cross-prediction isn't valid if gpt4o-mini is a distilled/quantised version of the same model (who knows)

I was also wondering if you have any plans to extend this work to inspect the new 'reasoning' models for introspection?

**Comment by felixbinder** [comment]
Amazing, thanks a lot! Curriculum learning is a great idea, and we’re excited to see what you find. It’s plausible that 4o mini is too small to do the task well. One thing that you could check for is how well it does on the `identity` response property (ie. just repeating the behavior itself). GPT-3.5 Turbo did decently here, indicating that while it can internally simulate, it might not be large enough to do that while also extracting a property on top of it. 

We’re definitely interested in o1 type models, but there are some challenges in adopting this particular argument into one that can be used with chain of thought (or similar). That is because models can adopt the strategy of ignoring all of the input except the hypothetical question, then “do the behavior”, then reason about the result that is now in context. This would be interesting, but also trivial in some sense. I think exploring chain of thought like that is certainly worth doing, but its interpretation re introspection is more tricky. I’m happy to chat more about potential ways of measuring introspective capability when using chain of thought (and what it means)

**Comment by pbevan1** [comment]
Thanks Felix, I’ll see what it looks like on the identity property. I was initially trying to mirror the val sets in the paper so hadn’t tested on that.

With respect to the reasoning models, I was also thinking perhaps the OpenAI o models might be additionally difficult to inspect because of the chain of thought being hidden. The google thinking or deepseek r1 models might be an option here since I believe the CoT is visible.

Perhaps it could be interesting to see how well the reasoning models perform introspection without their chain of thought. Could we somehow prompt/finetune the reasoning model to output no CoT, directly getting the answer as we would with previous models? Although from a quick go I could not do this with prompting so may not be realistic. One hypothesis would be that perhaps current reasoning models might have worse introspective capability since they are post-trained to reason externally, which perhaps could reduce the pressure to have internal reasoning/introspection. I'd say it'd be interesting if it swings either way though. Could be interesting to compare to the closest non-reasoning model. I.e. gemini-2.0-flash-thinking (without it’s CoT) vs gemini-2.0-flash

I'm also quite keen to hear what your thoughts were w.r.t measuring introspection in reasoning models when they're using CoT

**Comment by pbevan1** [comment]
newplot (1)

FWIW here are the results I got (including identity). So gpt-4o-mini does get above modal performance on a few of these, including the identity.

Can't see any signs of the curriculum learning approach helping though. I just added an argument in my fork that allows to set the order of the finetuning data based on response property, and set that to:

--property_order='["identity", "first_character", "second_character", "third_character", "is_even", "number_of_tokens", "is_either_a_or_c", "is_either_b_or_d", "matches_wealth_seeking", "matches_power_seeking"]' \

I have previously confirmed with someone from OpenAI that the order of finetuning data is respected behind the scenes so that shouldn't be an issue.

Never mind, I'm enjoying playing around with this, so might try some other experiments when I get a minute.

**Pull request merged**
